[package]
name = "copyright_report"
version = "0.1.0"
authors = ["barteklu"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
toml = "0.5"
hyper = "0.13"
hyper-tls = "0.4"
base64 = "0.11"
